# Compiler settings
CXX = g++
CXXFLAGS = -O3 -std=c++17 -Wall -g -I${HEADAS}/include -DNDEBUG
LDFLAGS = -L${HEADAS}/lib -lcfitsio -lwcs-7.3.1 -lpthread

# Output program
BIN = eroimgtool
# Autogenerated output
BUILD_DIR = ./build

# List of all C++ sources
SRC = attitude.cc badpix.cc common.cc geom.cc gti.cc main.cc coords.cc \
	image.cc build_poly.cc events.cc instpar.cc mask.cc proj_mode.cc \
	pars.cc poly_fill.cc image_mode.cc expos_mode.cc

# All .o files go to build dir.
OBJ = $(SRC:%.cc=$(BUILD_DIR)/%.o)
# Gcc/Clang will create these .d files containing dependencies.
DEP = $(OBJ:%.o=%.d)

# Default target named after the binary.
$(BIN) : $(BUILD_DIR)/$(BIN)

# Actual target of the binary - depends on all .o files.
$(BUILD_DIR)/$(BIN) : $(OBJ)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

# Include all .d files
-include $(DEP)

# Build target for every single object file.
# The potential dependency on header files is covered
# by calling `-include $(DEP)`.
# The -MMD flags additionaly creates a .d file with
# the same name as the .o file.
$(BUILD_DIR)/%.o : %.cc
	$(CXX) $(CXXFLAGS) -MMD -c $< -o $@

.PHONY : clean
# This should remove all generated files.
clean :
	-rm -f $(BUILD_DIR)/$(BIN) $(OBJ) $(DEP)
